version: "3.9"
services:
  web:
    image: rwinfosec-simple-web-app:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB: ${DB}
  nginx:
    depends_on:
      - web
    image: rwinfosec/modsecurity-nginx
    ports:
      - "80:80"
