version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dev_password
  web:
    image: rwinfosec-simple-web-app:<VERSION>
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
